import { api, getToken, supportedTab, type Status, type TabInfo } from './shared.js'
const $ = <T extends HTMLElement>(id: string) => document.getElementById(id) as T
const setup=$<HTMLElement>('setup'),controls=$<HTMLElement>('controls'),message=$<HTMLElement>('message'),workspace=$<HTMLSelectElement>('workspace'),tabList=$<HTMLElement>('tab-list')
async function init(){const token=await getToken();if(!token){setup.hidden=false;return}try{const status=await api<Status>('/api/status');controls.hidden=false;$('connection').textContent='Desktop connected';$('active').textContent=status.activeWorkspaceName||'No active workspace';workspace.replaceChildren(...status.workspaces.map(w=>new Option(w.name,w.id,w.id===status.activeWorkspaceId,w.id===status.activeWorkspaceId)));if(!status.workspaces.length){show('Create a workspace in the desktop app first.')}}catch(error){setup.hidden=false;$<HTMLInputElement>('token').value=token;show(String(error))}}
function show(text:string){message.textContent=text}
async function add(tabs:TabInfo[]){if(!workspace.value)return show('Choose a workspace first.');await api('/api/add-tabs',{method:'POST',body:JSON.stringify({workspaceId:workspace.value,tabs})});show(`Added ${tabs.length} tab${tabs.length===1?'':'s'}.`)}
$('save-token').onclick=async()=>{const token=$<HTMLInputElement>('token').value.trim();await chrome.storage.local.set({bridgeToken:token});location.reload()}
$('add-current').onclick=async()=>{try{const [tab]=await chrome.tabs.query({active:true,currentWindow:true});if(tab&&supportedTab(tab))await add([{title:tab.title||new URL(tab.url).hostname,url:tab.url}]);else show('This tab cannot be saved.')}catch(error){show(String(error))}}
$('load-tabs').onclick=async()=>{const tabs=(await chrome.tabs.query({currentWindow:true})).filter(supportedTab);tabList.replaceChildren(...tabs.map((tab,index)=>{const label=document.createElement('label');label.className='tab-item';label.innerHTML=`<input type="checkbox" data-index="${index}"><span><strong></strong><small></small></span>`;(label.querySelector('strong')!).textContent=tab.title||new URL(tab.url).hostname;(label.querySelector('small')!).textContent=tab.url;return label}));tabList.dataset.tabs=JSON.stringify(tabs.map(t=>({title:t.title||new URL(t.url).hostname,url:t.url})));$('tabs').hidden=false}
$('select-all').onclick=()=>tabList.querySelectorAll<HTMLInputElement>('input').forEach(input=>input.checked=true)
$('add-selected').onclick=async()=>{const tabs=JSON.parse(tabList.dataset.tabs||'[]') as TabInfo[];const selected=[...tabList.querySelectorAll<HTMLInputElement>('input:checked')].map(input=>tabs[Number(input.dataset.index)]).filter((tab):tab is TabInfo=>Boolean(tab));if(selected.length)await add(selected);else show('Select at least one tab.')}
void chrome.runtime.sendMessage('poll').catch(()=>{});void init()
